import turtle
radius=int(input("Enter the radius of the ring : "))
seperation=radius/5
turtle.goto(0,0)
turtle.left(90)
turtle.color("blue")
turtle.circle(radius)
turtle.penup()
turtle.goto((2*radius)+seperation,0)
turtle.pendown()
turtle.color("black")
turtle.circle(radius)
turtle.penup()
turtle.goto((4*radius)+(2*seperation),0)
turtle.pendown()
turtle.color("red")
turtle.circle(radius)
turtle.penup()
turtle.goto(radius+(seperation/2), -seperation-radius)
turtle.pendown()
turtle.color("yellow")
turtle.circle(radius)
turtle.penup()
turtle.goto((3*radius)+(seperation/2)+seperation, -seperation-radius)
turtle.pendown()
turtle.color("green")
turtle.circle(radius)
turtle.done()
