import turtle
length=int(input("Enter the length of the star : "))
turtle.left(72)
turtle.forward(length)
turtle.right(144)
turtle.forward(length)
turtle.right(144)
turtle.forward(length)
turtle.right(144)
turtle.forward(length)
turtle.right(144)
turtle.forward(length)
turtle.done()
